### ISSUE TITLE
ERROR:  While executing gem ... (NoMethodError) undefined method `request' for nil:NilClass on every version after 1.4.1

### ISSUE THREAD

**Issue by tiagonuneslx** [square/cocoapods-generate#128]
When I run `gem install cocoapods-generate`, it installs version 1.4.1 instead of the most recent (right now is 2.2.2).

My stack is currently incompatible with this version of `cocoapods-generate`. I get this error which was fixed in later releases:

`[!] cocoapods-generate requires CocoaPods >= 1.5.0`

When I run `gem install cocoapods-generate -v 2.2.2`, or any version after 1.4.1, I get:

> ERROR:  While executing gem ... (NoMethodError)
>     undefined method `request' for nil:NilClass

My stack:
```
M1 chip (arm64)
ruby 3.0.2p107
cocoapods (1.10.1)
```

**Comment by tomisacat** [comment]
Same problem here : (

**Comment by tiagonuneslx** [comment]
I have found a fix, but I don't remember what it was, unfortunately...

**Comment by tomisacat** [comment]
@tiagonuneslx I just downgrade to ruby 2.7 and everything works fine.

**Comment by tiagonuneslx** [comment]
Yes, that's what I did as well! I think it doesn't work for ruby 3.x
