### ISSUE TITLE
cocoapods-generate won't include sources shared across test_specs

### ISSUE THREAD

**Issue by mikehaney24** [square/cocoapods-generate#14]
Using cocoapods version 1.6.0.rc.2 and cocoapods-generate, I have two test_specs like below:

```
  s.test_spec 'UnitTests' do |test_spec|
    test_spec.requires_app_host = false
    test_spec.source_files = 'MyThing/Tests/Common/**/*.{h,m}'
    test_spec.source_files = 'MyThing/Tests/Unit/**/*.{h,m}'
  end

  s.test_spec 'EndToEndUnitTest' do |test_spec|
    test_spec.requires_app_host = true
    test_spec.source_files = 'MyThing/Tests/Common/**/*.{h,m}'
    test_spec.source_files = 'MyThing/Tests/EndToEnd/**/*.{h,m}'
  end
```

both test_specs have the line
`test_spec.source_files = 'MyThing/Tests/Common/**/*.{h,m}'`

but cocoapods-generate can't figure out which target the common sources belong to, so they are omitted from the project.

There's no obvious way to solve this problem. Creating an additional test_spec for the purposes of being a dependency of the other two test_specs doesn't work because the dependency isn't being compiled. So if you have something like a category used only for testing, its methods are missing.

**Comment by justinseanmartin** [comment]
The issue is using the `source_files` directive twice, where the second value set is overriding the first. You can supply an array of strings to a single `source_files` line instead. See the documentation here:

https://guides.cocoapods.org/syntax/podspec.html#source_files

**Comment by dnkoutso** [comment]
What @justinseanmartin is correct. The podspec is `ruby` you can also declare the files as a constant and then apply them. `s.source_files = SOURCE_FILES.dup` etc.

**Comment by mikehaney24** [comment]
How dumb of me! Thanks for the help!
