### ISSUE TITLE
Support forcing directory structure as project structure

### ISSUE THREAD

**Issue by mikehaney24** [square/cocoapods-generate#15]
The generated workspace uses test_spec names as logical folders in Xcode. This makes it difficult to pull out the sources that are common across test targets.

I have this directory structure, and would like the workspace to have this structure, too:
```
Tests/
- Common/
- Integration/
- Unit/
```

and these test specs:
- `Unit`
- `Integration`

The generated workspace builds this structure:
```
Integration/
- Common/
- Integration/

Unit/
- Unit/
```

AFAICT, `Common/` shows up in Integration because it's earlier in the alphabet. An additional flag, maybe `--ignore-spec-names` would be useful here.

Side note: I'm really loving cocoapods-generate, thanks for making the plugin!

**Comment by segiddins** [comment]
I think this is all done by CocoaPods proper, not `pod gen` -- we just build up a Podfile that CocoaPods then installs like normal.

**Comment by mikehaney24** [comment]
I think you're right. Thanks!
