### ISSUE TITLE
pod gen doesn't respect --local_sources for test_specs

### ISSUE THREAD

**Issue by mikehaney24** [square/cocoapods-generate#26]
My [podspec](https://github.com/firebase/firebase-ios-sdk/pull/3204/files#diff-ad29d1825624a22888c6487441382cc4) has these deps

```
  s.dependency 'FirebaseCoreDiagnosticsInterop', '~> 0.1'
  s.dependency 'GoogleDataTransportCCTSupport', '~> 0.1'
  s.dependency 'GoogleUtilities/Environment', '~> 6.0'
  s.dependency 'GoogleUtilities/Logger', '~> 6.0'
```

and this test spec
```
  s.test_spec 'unit' do |unit_tests|
    unit_tests.dependency 'FirebaseCore', '~> 6.0'
    unit_tests.requires_app_host = false
  end
```

but the local version of FirebaseCore isn't used--it's downloaded instead.

**Comment by paulb777** [comment]
We need this to support Firestore and test_specs, so I'll start on this one.

**Comment by segiddins** [comment]
I think https://github.com/square/cocoapods-generate/pull/43 will address this
