### ISSUE TITLE
Question: Repo layout for monorepo

### ISSUE THREAD

**Issue by a1cooke** [square/cocoapods-generate#47]
Hi,

Looking at using this plugin to support multiple modules developed in a single repo.  

I got a basic setup working with a single module, when adding more modules, the root of the repo started to feel cluttered with the `podspec`files in the root of the repo.

Any guidance on a clean way of supporting `podspec` files as a single source of truth while keeping the root of the repo clean?  

I tried out sub specs as an approach but didn't get any job with test specs being associated with a subspec.

If the answer is it's a necessary evil with Cocoapods, that totally fine.

Thanks for the awesome work!

**Comment by segiddins** [comment]
You can put Podspecs wherever in your repo you want! We have a structure like

```
Frameworks
  | A
    | A.podspec
    | ATesting.podspec
  | B
    | B.podspec
```

that we're overall pretty happy with

**Comment by a1cooke** [comment]
Thanks for the clarification @segiddins appreciate it!
