### ISSUE TITLE
Incompatible with CocoaPods 1.10.beta.1

### ISSUE THREAD

**Issue by paulb777** [square/cocoapods-generate#68]
`cocoapods-generate requires CocoaPods >= 1.5.0`

Detailed log in https://github.com/firebase/firebase-ios-sdk/runs/885053344

**Comment by paulb777** [comment]
https://metaredux.com/posts/2018/10/28/a-better-way-to-compare-versions-in-ruby.html describes a fix, but I'm not sure how to test in development.

**Comment by chris-hatton** [comment]
Closed but not released?  Lack of a release for this fix is now impacting major use cases including Kotlin/iOS.
