### ISSUE TITLE
New release is required to resolve incompatibility with current iOS toolchain

### ISSUE THREAD

**Issue by chris-hatton** [square/cocoapods-generate#83]
As of October 2020, the currently released `cocoapods-generate` gem  is incompatible with the latest Cocoapods 1.10.0.
This has been raised and resolved in `master` branch as a separate issue (#68), but the lack of a release has become all the more pressing now, because Cocoapods `1.9.3` exhibits [other incompatibilities](https://github.com/CocoaPods/CocoaPods/issues/10059) with newest Xcode 12, which are resolved in Cocoapods `1.10.0`.
Last release of `cocoapods-generate` was April 2020 - can we have some idea when a new release is likely/planned?  Current workaround for working with latest Xcode is to build/install `master` gem.

**Comment by dnkoutso** [comment]
2.0.1 was released! please let us know if something else is wrong or missing.
