### ISSUE TITLE
pod gen not working with cocoapods 1.10.0

### ISSUE THREAD

**Issue by HashimPhilips** [square/cocoapods-generate#84]
update cocoapods to the latest version ie 1.10.0
gem install cocoapods
gem install cocoapods-generate
pod gen will fail
[!] cocoapods-generate requires CocoaPods >= 1.5.0
cocoapods-generate version check logic is wrong  
actual result 1.10.0 < 1.5.0
expected result  1.10.0 > 1.5.0

update: it seems like issue is fixed in master branch when this will be available as release

**Comment by paulb777** [comment]
Duplicate of #68 and fixed in #69, but not yet released ...

**Comment by dnkoutso** [comment]
2.0.1 was released today.
